# Generated by Django 4.2.5 on 2024-03-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Singing_Event_Booking_System",
            "0003_remove_booking_date_created_booking_event_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="event_id",
            field=models.IntegerField(),
        ),
    ]
