# Generated by Django 4.2.5 on 2024-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Singing_Event_Booking_System", "0004_alter_booking_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="event_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="event_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
